version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    restart: always
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT__SERVICE__API_KEY}
    volumes:
      - /home/qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"

  context-redis:
    image: redis:7.2.4-alpine
    restart: always
    command: redis-server
    volumes:
      - /home/redis_storage:/data
    ports:
      - "26481:6379"

  mongo:
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /home/mongodbdata-apps:/data/db
    ports:
      - "27027:27017"

  core:
    build:
      context: ../../core
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=local
      - APP_ENV=local
      - PORT=${PORT}
      - JWT_SALT=${JWT_SALT}
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_RECORDINGS_BUCKET_NAME=${S3_RECORDINGS_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - WEB_CLIENT_URL=${WEB_CLIENT_URL}
      - QDRANT_URL=${QDRANT_URL}
      - YANDEX_API_TOKEN=${YANDEX_API_TOKEN}
      - YANDEX_ML_FOLDER_ID=${YANDEX_ML_FOLDER_ID}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
    depends_on:
      - mongo
      - qdrant
      - context-redis
    links:
      - mongo
      - qdrant
      - context-redis
    ports:
      - "3031:3001"

  web-client:
    build:
      context: ../../web-client
      dockerfile: Dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_APP_ENV=local
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    depends_on:
      - core
    links:
      - core
    ports:
      - "3041:3001"

networks:
  default:
    external:
      name: mini-apps