version: "3.8"

services:
  mongo:
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: my_password
    volumes:
      - /etc/mongodbdata-apps:/data/db
    ports:
      - "27027:27017"

networks:
  default:
    external:
      name: mini-apps