version: "3.8"

services:
  mongo:
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: my_password
    volumes:
      - /Users/nikitakrainev/Desktop/HSEDiplom/mongodbdata-apps:/data/db
    ports:
      - "27027:27017"

  qdrant:
    image: qdrant/qdrant
    restart: always
    environment:
      - QDRANT__SERVICE__API_KEY=dfsgwg%23435dvffdgb
    volumes:
      - /Users/nikitakrainev/Desktop/HSEDiplom/qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"

  context-redis:
    image: redis:7.2.4-alpine
    restart: always
    command: redis-server
    ports:
      - "26481:6379"
