name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: docker-compose --compatibility -f deploy/prod/docker-compose.yml up -d --force-recreate --build
