name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:

        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: docker-compose --compatibility -f deploy/prod/docker-compose.yml up -d --force-recreate --build
          env:
            PORT: ${{ vars.PORT }}
            JWT_SALT: ${{ vars.JWT_SALT }}
            MONGO_CONNECTION_STRING: ${{ vars.MONGO_CONNECTION_STRING }}
            S3_ACCESS_KEY_ID: ${{ vars.S3_ACCESS_KEY_ID }}
            S3_SECRET_ACCESS_KEY: ${{ vars.S3_SECRET_ACCESS_KEY }}
            S3_RECORDINGS_BUCKET_NAME: ${{ vars.S3_RECORDINGS_BUCKET_NAME }}
            S3_REGION: ${{ vars.S3_REGION }}
            WEB_CLIENT_URL: ${{ vars.WEB_CLIENT_URL }}
            QDRANT_URL: ${{ vars.QDRANT_URL }}
            YANDEX_API_TOKEN: ${{ vars.YANDEX_API_TOKEN }}
            YANDEX_ML_FOLDER_ID: ${{ vars.YANDEX_ML_FOLDER_ID }}
            LANGSMITH_TRACING: ${{ vars.LANGSMITH_TRACING }}
            NEXT_PUBLIC_APP_ENV: ${{ vars.NEXT_PUBLIC_APP_ENV }}
            NEXT_PUBLIC_BACKEND_URL: ${{ vars.NEXT_PUBLIC_BACKEND_URL }}
            QDRANT__SERVICE__API_KEY: ${{ vars.QDRANT__SERVICE__API_KEY }}
            MONGO_INITDB_ROOT_USERNAME: ${{ vars.MONGO_INITDB_ROOT_USERNAME }}
            MONGO_INITDB_ROOT_PASSWORD: ${{ vars.MONGO_INITDB_ROOT_PASSWORD }}
            ME_BOT_TOKEN: ${{ vars.ME_BOT_TOKEN }}
            NEBIUS_BASE_URL: ${{ vars.NEBIUS_BASE_URL }}
            NEBIUS_SECRET_KEY: ${{ vars.NEBIUS_SECRET_KEY }}
            REDIS_HOST: ${{ vars.REDIS_HOST }}
            REDIS_PORT: ${{ vars.REDIS_PORT }}
            REDIS_USERNAME: ${{ vars.REDIS_USERNAME }}
            REDIS_PASSWORD: ${{ vars.REDIS_PASSWORD }}
            TG_BOT_WEBHOOK: ${{ vars.TG_BOT_WEBHOOK }}
